title: Teaching Repository
theme: just-the-docs
url: "https://robertrakay.github.io"
baseurl: "/vyucba"
search_enabled: true
color_scheme: light
aux_links:
  "GitHub": "https://github.com/robertrakay/vyucba"
