title: Teaching Repository
theme: just-the-docs
url: https://yourusername.github.io/vyucba
baseurl: ""
search_enabled: true
color_scheme: light
aux_links:
  "GitHub": "https://github.com/yourusername/vyucba"
