title: Teaching Repository
description: "Educational materials for various subjects"
remote_theme: "cotes2020/jekyll-theme-chirpy"

url: "https://robertrakay.github.io"
baseurl: "/vyucba"

markdown: kramdown

search_enabled: true
color_scheme: light

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

aux_links:
  "GitHub Repository": "https://github.com/robertrakay/vyucba"

navbar:
  - title: üè† Home
    url: /
  - title: üìò Subjects
    sublinks:
      - title: Electrotechnics
        url: /Electrotechnics_and_electrical_engineering/
      - title: Automation
        url: /Automation_and_automation_technology/
      - title: Cybernetics
        url: /Cybernetics_and_Informatics/
      - title: Mechatronics
        url: /Mechatronics_-_Microprocessors/
      - title: Digitaliz√°cia Priemyslu
        url: /Digitaliz√°cia_Priemyslu/
      - title: Lek√°rska elektronika
        url: /Lek√°rska_elektronika/
      - title: Logick√© Riadiace Syst√©my
        url: /Logick√©_Riadiace_Syst√©my/
      - title: Projektov√° Dokument√°cia
        url: /Projektov√°_Dokument√°cia/
      - title: Prostriedky Priemyselnej Automatiz√°cie
        url: /Prostriedky_Priemyselnej_Automatiz√°cie/
      - title: Z√°klady Programovania
        url: /Z√°klady_Programovania/
